[project]
name = "syntropai-insight"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gradio>=5.36.2",
    "openai>=1.95.0",
    "pypdf2>=3.0.1",
    "python-dotenv>=1.1.1",
]
